### ISSUE TITLE
binary-instances-1 test suite failure

### ISSUE THREAD

**Issue by peti** [phadej/binary-orphans#45] opened 2020-03-06 19:06 UTC
Citing from https://hydra.nixos.org/build/114007066/nixlog/1:

~~~~
  CI Text:            FAIL
    *** Failed! Falsified (after 76 tests and 8 shrinks):
    "\43949"
    "\43949" /= "\5085"
    Use --quickcheck-replay=455351 to reproduce.
~~~~

**Comment by phadej** [comment] 2020-03-06 21:21
Duplicate of https://github.com/phadej/binary-instances/issues/7

**Closed as completed by phadej** 2020-03-06 21:21 UTC
